### ISSUE TITLE
建议 在文档中告知需要额外安装的依赖 在mac 中需要安装libuv

### ISSUE THREAD

**Issue by zzhgithub** [guenchi/Igropyr#4]
如果报错为
httpc.c:27:10: fatal error: 'uv.h' file not found
那么需要安装：
```brew install libuv```

**Comment by guenchi** [comment]
```Igropyr dependence libuv, make sure you have installed it.```

我相信应该有提及

**Comment by zzhgithub** [comment]
额 ok 我没有认真读
